# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_booking
spring.datasource.username=postgres
spring.datasource.password=2205

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Liquibase
#spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
#spring.liquibase.enabled=true

# Thymeleaf
spring.thymeleaf.cache=false

# Logging
logging.level.com.hotelbooking=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=DEBUG

# Actuator
management.endpoints.web.exposure.include=health,metrics,info

# Server
server.port=8080

# JWT
app.jwtSecret=mySuperSecretKeyForJWTTokenGeneration2026HotelBookingProject
app.jwtExpirationMs=86400000